### ISSUE TITLE
Stuck on "Connecting to Battle.Net"

### ISSUE THREAD

**Issue by Dougoll** [Chobotz/D2R-multiclient-tools#2]
Hi! 
With singleclient launch I'm stuck at "Connecting to Batlle.net"  
With multiclient launch it reaches character selection in offline mode. When I click Online I get the message "We couldn't verify your account with that information"

I made sure that the Bnet launcher is updated.
I don't use the Authenticator either.

Any idea what could cause these issues?

Thanks!

**Comment by Chobotz** [comment]
Step 2, you need to configure the credentials properly, verify that password does not contain ; character, triple check psw is correct.

"we could not verify the information" means you put wrong battle net email or password

In the case you triggered battle net account protection (captcha), open normal bnet launcher, solve captcha, make sure you can normally log in, make sure you disabled Battle net authenticator.

You can also try to delete the battle net cache:
C:\Users\User\AppData\Local\Battle.net\Cache\

**Comment by Dougoll** [comment]
Hi, thanks for the feedback.

Passwords are more than tripled checked, the character ; is not in any passwords, I have no captcha to solve when I manually login and I deleted the cache. I still have the same result...I don't understand why I can't make it work.

**Comment by Dougoll** [comment]
Alright, no problem. Thanks for your time!
